# Generated by Django 5.2 on 2025-04-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_author_article_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
    ]
