# Generated by Django 5.2 on 2025-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_author_remove_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
